### ISSUE TITLE
Add build instructions.

### ISSUE THREAD

**Issue by Anonymous2716** [dubrowgn/renamer#1]
this seems useful to me. Specially when i was doing  something similar but instead I had to write my own java program which is not feature rich as this one. you currently distributing x64 binaries . but I need this on my Android phone which is aarch64 . so with the build instructions I could build the software on my phone and give it a go. What do you think?

**Comment by dubrowgn** [comment]
I'm honestly not sure if Qt builds for Android (I've never looked into it), so unfortunately I don't have build instructions for that environment. I'd be happy to add them if you managed to figure it out though.

**Comment by Anonymous2716** [comment]
In termux I think can manage. And even if termux doesn't have QT builds/packages I can always do it in proot environment. Or at least try.

**Comment by Anonymous2716** [comment]
@dubrowgn it was easier than I tht to build the application just a few commands.
```
❯ qmake renamer.pro
❯ make
```
 And i build it in termux (https://github.com/termux). Tho I have not tested yet. Thanks.

![s](https://user-images.githubusercontent.com/78570872/224509010-afc242e8-7960-43e5-a344-a0a95ae9ece0.png)
